name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - release-*
      - v[0-9].[0-9]+.[0-9]+

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  production-check:
    runs-on: ubuntu-latest
    if: startsWith(github.ref , 'refs/tags')
    outputs:
      trigger: ${{ steps.check.outputs.trigger }}
    steps:
      - id: check
        run: |
          if
            [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
            [[ ${{ github.ref }} =~ ^refs/tags/release-.+ ]]; then
            echo "trigger=true" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - run: echo "building image"

  deploy-dev:
    uses: ./.github/workflows/deploy-cf-cr.yaml
    needs:
      - build

  deploy-prod:
    uses: ./.github/workflows/deploy-cf-cr.yaml
    needs:
      - build
      - production-check
    if: needs.production-check.outputs.trigger == 'true'
