name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - release-*
      - v[0-9].[0-9]+.[0-9]+

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - run: echo "building image"

  deploy-dev:
    uses: ./.github/workflows/deploy-cf-cr.yaml
    needs:
      - build

  production-checker:
    runs-on: ubuntu-latest
    outputs:
      production_trigger: ${{ steps.step1.outputs.production_trigger }}
    steps:
      - id: checker
        run: echo "production_trigger=true" >> $GITHUB_OUTPUT

  deploy-prod:
    uses: ./.github/workflows/deploy-cf-cr.yaml
    needs:
      - build
      - production-checker
    if: needs.production-checker.outputs.production_trigger == 'true'
