name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - release-*
      - v[0-9].[0-9]+.[0-9]+

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    runs-on: ubuntu-latest
    needs:
      - test

  deploy:
    uses: ./.github/workflows/deploy-cloud-run.yaml


  # cloud-run-production:
  #   uses: ./.github/workflows/deploy-cloud-run.yaml
  #   needs:
  #     - build
  #   if: github.ref != 'refs/heads/master'
